/** @type {import('tailwindcss').Config} */
// ============================================================
// AgroNet Africa — Design System
// Generated by UI/UX Pro Max Skill (Rules #23 + #26)
// Pattern: Feature-Rich Showcase + Conversion-Optimized
// Style:   Organic Biophilic + Flat Design
// Colors:  Earth Green #4A7C23 + Brown #6B4226 + Sky #38BDF8
// Fonts:   Poppins (display) + Inter (body)
// ============================================================
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        agro: {
          50:  '#f4f9ed',
          100: '#e5f1d0',
          200: '#cce4a5',
          300: '#a8cf6b',
          400: '#84b83e',
          500: '#649e25',
          600: '#4A7C23',
          700: '#3a6119',
          800: '#2f4d15',
          900: '#283f14',
          950: '#142209',
        },
        earth: {
          50:  '#fdf5ef',
          100: '#fae8d6',
          200: '#f4ceac',
          300: '#ecac77',
          400: '#e28040',
          500: '#da6424',
          600: '#cc4e1a',
          700: '#a93a17',
          800: '#8a3019',
          900: '#6B4226',
          950: '#3d2010',
        },
        soil: {
          50:  '#fdf8f0',
          100: '#f5ead6',
          200: '#ebd5ad',
          300: '#d4a96d',
          400: '#c08840',
          500: '#a67032',
          600: '#8a5a29',
          700: '#6d4520',
          800: '#573618',
          900: '#422912',
        },
        sky: {
          50:  '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38BDF8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
      },
      fontFamily: {
        sans:    ['Inter', 'system-ui', 'sans-serif'],
        display: ['Poppins', 'system-ui', 'sans-serif'],
        mono:    ['JetBrains Mono', 'monospace'],
      },
      boxShadow: {
        'biophilic-sm': '0 2px 8px -2px rgba(74,124,35,0.15), 0 1px 3px -1px rgba(74,124,35,0.10)',
        'biophilic':    '0 4px 20px -4px rgba(74,124,35,0.20), 0 2px 8px -2px rgba(74,124,35,0.12)',
        'biophilic-lg': '0 8px 32px -6px rgba(74,124,35,0.25), 0 4px 12px -3px rgba(74,124,35,0.15)',
        'glow-green':   '0 0 20px rgba(74,124,35,0.35)',
        'glow-earth':   '0 0 20px rgba(107,66,38,0.25)',
      },
      animation: {
        'float':         'float 6s ease-in-out infinite',
        'float-delayed': 'float 6s ease-in-out 2s infinite',
        'fade-in':       'fadeIn 0.5s ease-out forwards',
        'fade-in-up':    'fadeInUp 0.6s ease-out forwards',
        'fade-in-down':  'fadeInDown 0.5s ease-out forwards',
        'slide-in-left': 'slideInLeft 0.5s ease-out forwards',
        'slide-in-right':'slideInRight 0.5s ease-out forwards',
        'scale-in':      'scaleIn 0.4s ease-out forwards',
        'pulse-gentle':  'pulseGentle 3s ease-in-out infinite',
        'gradient-shift':'gradientShift 8s ease infinite',
        'leaf-sway':     'leafSway 4s ease-in-out infinite',
        'shimmer':       'shimmer 2s linear infinite',
        'reveal':        'reveal 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
      keyframes: {
        float:         { '0%, 100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-16px)' } },
        fadeIn:        { from: { opacity: '0' }, to: { opacity: '1' } },
        fadeInUp:      { from: { opacity: '0', transform: 'translateY(24px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        fadeInDown:    { from: { opacity: '0', transform: 'translateY(-16px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideInLeft:   { from: { opacity: '0', transform: 'translateX(-32px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        slideInRight:  { from: { opacity: '0', transform: 'translateX(32px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        scaleIn:       { from: { opacity: '0', transform: 'scale(0.92)' }, to: { opacity: '1', transform: 'scale(1)' } },
        pulseGentle:   { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.65' } },
        gradientShift: { '0%, 100%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' } },
        leafSway:      { '0%, 100%': { transform: 'rotate(-3deg)' }, '50%': { transform: 'rotate(3deg)' } },
        shimmer:       { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        reveal:        { from: { opacity: '0', transform: 'translateY(20px) scale(0.97)' }, to: { opacity: '1', transform: 'translateY(0) scale(1)' } },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'earth-gradient':  'linear-gradient(135deg, #4A7C23 0%, #3a6119 50%, #6B4226 100%)',
        'sky-gradient':    'linear-gradient(135deg, #4A7C23 0%, #38BDF8 100%)',
      },
    },
  },
  plugins: [],
}
